name: robodiff_1
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
  - xformers
dependencies:
  - python=3.9
  - pip=22.2.2
  - cuda-toolkit=12.1.0
  - pytorch=2.1.0
  - torchvision=0.16.0
  # - pytorch-cuda=12.1
  - pytorch3d=0.7.5
  - numpy=1.23.3
  - numba==0.56.4
  # - scipy==1.9.1
  # - py-opencv=4.6.0
  - cffi=1.15.1
  - ipykernel=6.16
  - zarr=2.12.0
  - numcodecs=0.10.2
  - h5py=3.7.0
  - hydra-core=1.2.0
  - einops=0.4.1
  - tqdm=4.64.1
  - dill=0.3.5.1
  - scikit-video=1.1.11
  - scikit-image=0.19.3
  - gym=0.21.0
  - pymunk=6.2.1
  - wandb=0.16.1
  - threadpoolctl=3.1.0
  - shapely=1.8.4
  - cython=0.29.32
  - imageio=2.22.0
  - imageio-ffmpeg=0.4.7
  - termcolor=2.0.1
  - tensorboard=2.10.1
  - tensorboardx=2.5.1
  - psutil=5.9.2
  - click=8.0.4
  - boto3=1.24.96
  - accelerate=0.13.2
  - datasets=2.6.1
  - diffusers=0.11.1
  - av=10.0.0
  - cmake=3.24.3
  # trick to avoid cpu affinity issue described in https://github.com/pytorch/pytorch/issues/99625
  - llvm-openmp=14
  # trick to force reinstall imagecodecs via pip
  - imagecodecs==2022.8.8
  - xformers
  # pip install imagecodecs==2022.8.8 sapien==2.2.2 pyperclip==1.8.2 open3d==0.17.0 plotly==5.17.0 PyMCubes==0.1.4 trimesh==4.0.0 git+https://github.com/facebookresearch/segment-anything.git accelerate==0.20.3 scipy==1.9.1 opencv-python==4.6.0.66 git+https://github.com/WangYixuan12/GroundingDINO.git gdown==4.7.1 git+https://github.com/fishbotics/urchin.git@fishbotics-merge pyrealsense2==2.54.2.5684 atomics==1.0.2 opencv-contrib-python==4.8.1.78 pynput==1.7.6 pybullet==3.2.6 torch-cluster -f https://data.pyg.org/whl/torch-2.1.0+cu121.html
  - pip:
      # - ray[default,tune]==2.2.0
      # requires mujoco py dependencies libosmesa6-dev libgl1-mesa-glx libglfw3 patchelf
      # - free-mujoco-py==2.1.6
      # - pygame==2.1.2
      # - pybullet-svl==3.1.6.4
      # - robosuite @ https://github.com/cheng-chi/robosuite/archive/277ab9588ad7a4f4b55cf75508b44aa67ec171f0.tar.gz
      # - robomimic==0.2.0
      # - pytorchvideo==0.1.5
      # pip package required for jpeg-xl
      - imagecodecs==2022.9.26
      # - r3m @ https://github.com/facebookresearch/r3m/archive/b2334e726887fa0206962d7984c69c5fb09cceab.tar.gz
      # - dm-control==1.0.9
      - sapien==2.2.2
      - pyperclip==1.8.2
      - open3d==0.18.0
      - plotly==5.17.0
      - PyMCubes==0.1.4
      - trimesh==4.0.0
      - git+https://github.com/facebookresearch/segment-anything.git
      - accelerate==0.20.3
      - scipy==1.9.1
      - matplotlib==3.8.2
      - opencv-contrib-python==4.9.0.80
      # - git+https://github.com/WangYixuan12/GroundingDINO.git
      - git+https://github.com/IDEA-Research/GroundingDINO.git
      # - git+https://github.com/facebookresearch/pytorch3d.git
      # - xformers --index-url https://download.pytorch.org/whl/cu118
      - gdown==4.7.1
      - urchin==0.0.27 # urdfpy
      - pyrealsense2==2.54.2.5684
      - atomics==1.0.2
      - torch-cluster -f https://data.pyg.org/whl/torch-2.1.0+cu121.html
      - pynput==1.7.6
      - pybullet==3.2.6
      - supervision
