_target_: diffusion_policy.workspace.train_diffusion_unet_hybrid_workspace.TrainDiffusionUnetHybridWorkspace
is_real: true
data_root: /media/yixuan_2T/diffusion_policy
dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 2
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 16
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 2
name: train_diffusion_unet_hybrid
obs_as_global_cond: true
shape_meta:
  action:
    shape:
    - 10
  obs:
    d3fields:
      shape:
      - 5 # C
      - 1000 # N
      type: spatial
      info:
        feats_type: no_feats # no_feats, full, pca
        reference_frame: robot
        use_seg: false
        use_dino: false
        distill_dino: true
        distill_obj: ${obj_name}_vis
        rob_pcd: true
        view_keys:
        - camera_0
        - camera_1
        - camera_2
        - camera_3
        query_texts:
        - cup
        - pad
        query_thresholds:
        - 0.3
        N_per_inst: 100
        boundaries:
          x_lower: -0.32
          x_upper: 0.10
          y_lower: -0.35
          y_upper: 0.15
          z_lower: 0.02
          z_upper: 0.5
        resize_ratio: 0.5
task:
  abs_action: true
  dataset:
    _target_: diffusion_policy.dataset.real_dataset.RealDataset
    dataset_dir: ${data_root}/data/real_aloha_demo/${dataset_name}
    vis_input: false
    horizon: 16
    pad_after: 7
    pad_before: 1
    rotation_rep: rotation_6d
    seed: 42
    n_obs_steps: 2
    robot_name: trossen_vx300s_v3
    expected_labels: [background, cup, pad]
    exclude_colors: [yellow]
    shape_meta:
      action:
        shape:
        - 10
      obs:
        d3fields:
          shape:
          - 5 # C
          - 1000 # N
          type: spatial
          info:
            feats_type: no_feats # no_feats, full, pca
            reference_frame: robot
            use_seg: false
            use_dino: false
            distill_dino: true
            distill_obj: ${obj_name}_vis
            rob_pcd: true
            view_keys:
            - camera_0
            - camera_1
            - camera_2
            - camera_3
            query_texts:
            - cup
            - pad
            query_thresholds:
            - 0.3
            N_per_inst: 100
            boundaries:
              x_lower: -0.32
              x_upper: 0.10
              y_lower: -0.35
              y_upper: 0.15
              z_lower: 0.02
              z_upper: 0.5
            resize_ratio: 0.5
    use_cache: true
    val_ratio: 0.1
  dataset_dir: ${data_root}/data/real_aloha_demo/${dataset_name}
  name: ${task_name}
  shape_meta:
    action:
      shape:
      - 10
    obs:
      d3fields:
        shape:
        - 5 # C
        - 1000 # N
        type: spatial
        info:
          feats_type: no_feats # no_feats, full, pca
          reference_frame: robot
          use_seg: false
          use_dino: false
          distill_dino: true
          distill_obj: ${obj_name}_vis
          rob_pcd: true
          view_keys:
          - camera_0
          - camera_1
          - camera_2
          - camera_3
          query_texts:
          - cup
          - pad
          query_thresholds:
          - 0.3
          N_per_inst: 100
          boundaries:
            x_lower: -0.32
            x_upper: 0.10
            y_lower: -0.35
            y_upper: 0.15
            z_lower: 0.02
            z_upper: 0.5
          resize_ratio: 0.5
  task_name: ${task_name}
task_name: heatmap_vis_${obj_name}
dataset_name: heatmap_vis_${obj_name}
obj_name: mug
