_target_: diffusion_policy.workspace.train_diffusion_unet_hybrid_workspace.TrainDiffusionUnetHybridWorkspace
is_real: false
robot_name: panda
data_root: /root/lyt/diffusion_policy_code/general_dp
trial_name: mask_attention
dataset_dir: /mnt/data/diffusion_data/collection_data/hang_mug_demo_360_multi
# output_dir: /mnt/data/diffusion_policy/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}_multi_no_seg_no_dino_N_4000_pn2.1_r_0.04
output_dir: /mnt/data/diffusion_policy/${now:%Y.%m.%d}/${trial_name}
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 2
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 16
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: ${trial_name}
  project: diffusion_attention
  resume: false
  tags:
    - train_diffusion_unet_hybrid
    - ${task_name}
    - sim
    - default
multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/train_diffusion_unet_hybrid_${task_name}
  wandb_name_base: ${trial_name}
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 2
name: train_diffusion_unet_hybrid
obs_as_global_cond: true
optimizer:
  _target_: torch.optim.AdamW
  betas:
    - 0.95
    - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.diffusion_unet_hybrid_image_policy.DiffusionUnetHybridImagePolicy
  output_type: pose
  cond_predict_scale: true
  diffusion_step_embed_dim: 128
  down_dims:
    - 512
    - 1024
    - 2048
  eval_fixed_crop: true
  horizon: 16
  kernel_size: 5
  n_action_steps: 8
  n_groups: 8
  n_obs_steps: 2
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    beta_start: 0.0001
    clip_sample: true
    num_train_timesteps: 100
    prediction_type: epsilon
    variance_type: fixed_small
  num_inference_steps: 100
  obs_as_global_cond: true
  obs_encoder_group_norm: true
  feat_proc: none # none, linear, mlp
  compositional: false
  shape_meta:
    action:
      shape:
        - 10
      key: cartesian_action
    obs:
      d3fields:
        shape:
          - 4 # C
          - 1600 # N
        type: spatial
        info:
          feats_type: no_feats # no_feats, full, pca # no_feats, full, pca
          reference_frame: world
          use_seg: true
          use_dino: false
          use_attn: true
          distill_dino: false
          rob_pcd: true
          view_keys:
            - left_bottom_view
            - right_bottom_view
            - left_top_view
            - right_top_view
          query_texts:
            - mug tree
            - red mug
          query_thresholds:
            - 0.3
          N_per_inst: 400
          boundaries:
            x_lower: -0.35
            x_upper: 0.35
            y_lower: -0.3
            y_upper: 0.5
            z_lower: 0.005
            z_upper: 0.5
          resize_ratio: 0.5
shape_meta:
  action:
    shape:
      - 10
    key: cartesian_action
  obs:
    d3fields:
      shape:
        - 4 # C
        - 1600 # N
      type: spatial
      info:
        feats_type: no_feats # no_feats, full, pca # no_feats, full, pca
        reference_frame: world
        use_seg: true
        use_dino: false
        use_attn: true
        distill_dino: false
        rob_pcd: true
        view_keys:
          - left_bottom_view
          - right_bottom_view
          - left_top_view
          - right_top_view
        query_texts:
          - mug tree
          - red mug
        query_thresholds:
          - 0.3
        N_per_inst: 400
        boundaries:
          x_lower: -0.35
          x_upper: 0.35
          y_lower: -0.3
          y_upper: 0.5
          z_lower: 0.005
          z_upper: 0.5
        resize_ratio: 0.5dis
task:
  abs_action: true
  dataset:
    _target_: diffusion_policy.dataset.sapien_dataset.SapienDataset
    dataset_dir: ${dataset_dir}
    vis_input: false
    device: cuda:0
    horizon: 16
    pad_after: 7
    pad_before: 1
    rotation_rep: rotation_6d
    seed: 42
    n_obs_steps: 2
    robot_name: panda
    expected_labels: [background, soda, pad]
    shape_meta:
      action:
        shape:
          - 10
        key: cartesian_action
      obs:
        d3fields:
          shape:
            - 4 # C
            - 1600 # N
          type: spatial
          info:
            feats_type: no_feats # no_feats, full, pca # no_feats, full, pca
            reference_frame: world
            use_seg: true
            use_dino: false
            use_attn: true
            distill_dino: false
            rob_pcd: true
            view_keys:
              - left_bottom_view
              - right_bottom_view
              - left_top_view
              - right_top_view
            query_texts:
              - mug tree
              - red mug
            query_thresholds:
              - 0.3
            N_per_inst: 400
            boundaries:
              x_lower: -0.35
              x_upper: 0.35
              y_lower: -0.3
              y_upper: 0.5
              z_lower: 0.005
              z_upper: 0.5
            resize_ratio: 0.5
    use_cache: true
    val_ratio: 0.1
    manual_val_mask: false
    manual_val_start: 200
  dataset_dir: ${dataset_dir}
  name: ${task_name}
  env_runner:
    _target_: diffusion_policy.env_runner.sapien_series_image_runner.SapienSeriesImageRunner
    output_type: pose
    pca_name: can
    abs_action: true
    crf: 22
    dataset_dir: ${dataset_dir}
    fps: 10
    max_steps: 800
    n_action_steps: 8
    n_envs: null
    n_obs_steps: 2
    n_test: 0
    n_test_vis: 0
    n_train: 0
    n_train_vis: 0
    train_obj_ls:
      - nescafe_mug
    test_obj_ls:
      - nescafe_mug
    past_action: false
    render_obs_keys:
      # - front_view
      # - right_view
      - left_bottom_view
      - right_bottom_view
      - left_top_view
      - right_top_view
    policy_keys:
      - d3fields
    # - ee_pos
    shape_meta:
      action:
        shape:
          - 10
        key: cartesian_action
      obs:
        d3fields:
          shape:
            - 4 # C
            - 1600 # N
          type: spatial
          info:
            feats_type: no_feats # no_feats, full, pca # no_feats, full, pca
            reference_frame: world
            use_seg: true
            use_dino: false
            use_attn: true
            distill_dino: false
            rob_pcd: true
            view_keys:
              - left_bottom_view
              - right_bottom_view
              - left_top_view
              - right_top_view
            query_texts:
              - mug tree
              - red mug
            query_thresholds:
              - 0.3
            N_per_inst: 400
            boundaries:
              x_lower: -0.35
              x_upper: 0.35
              y_lower: -0.3
              y_upper: 0.5
              z_lower: 0.005
              z_upper: 0.5
            resize_ratio: 0.5
    test_start_seed: 100000
    tqdm_interval_sec: 1.0
    train_start_idx: 0
  shape_meta:
    action:
      shape:
        - 10
      key: cartesian_action
    obs:
      d3fields:
        shape:
          - 4 # C
          - 1600 # N
        type: spatial
        info:
          feats_type: no_feats # no_feats, full, pca # no_feats, full, pca
          reference_frame: world
          use_seg: true
          use_dino: false
          use_attn: true
          distill_dino: false
          rob_pcd: true
          view_keys:
            - left_bottom_view
            - right_bottom_view
            - left_top_view
            - right_top_view
          query_texts:
            - mug tree
            - red mug
          query_thresholds:
            - 0.3
          N_per_inst: 400
          boundaries:
            x_lower: -0.35
            x_upper: 0.35
            y_lower: -0.3
            y_upper: 0.5
            z_lower: 0.005
            z_upper: 0.5
          resize_ratio: 0.5
  task_name: ${task_name}
task_name: can_original_DP
dataset_name: can_demo_1_multi
training:
  checkpoint_every: 60
  debug: false
  device: cuda
  device_id: 1
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 2000
  max_train_steps: null
  max_val_steps: null
  num_epochs: 600
  resume: false
  rollout_every: 100
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 50
val_dataloader:
  batch_size: 32
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false
